"use client";

import { useEffect, useRef, useState } from "react";

type Dashboard = { cameras:{total:number;online:number}; incidents:{active:number;critical:number}; events_today:number; sectors:{name:string;status:string;incidents:number}[] };
type Incident = {id:string;type:string;camera_id:string;sector:string;timestamp:string;object_type:string;track_id:string;confidence:number;risk_score:number;severity:string;status:string;reason:string[]};
type Detection = {track_id:number|null;label:string;confidence:number;bbox:number[]};
type CameraDevice = {deviceId:string;label:string};
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export default function Home(){
  const [dashboard,setDashboard]=useState<Dashboard|null>(null); const [incidents,setIncidents]=useState<Incident[]>([]); const [selected,setSelected]=useState<Incident|null>(null); const [apiOnline,setApiOnline]=useState(false); const [live,setLive]=useState<Detection[]>([]); const [stream,setStream]=useState("disconnected"); const [source,setSource]=useState("Phone / Webcam");
  const [cameraRunning,setCameraRunning]=useState(false); const [cameraError,setCameraError]=useState(""); const [devices,setDevices]=useState<CameraDevice[]>([]); const [deviceId,setDeviceId]=useState("");
  const es=useRef<EventSource|null>(null); const videoRef=useRef<HTMLVideoElement|null>(null); const canvasRef=useRef<HTMLCanvasElement|null>(null); const mediaRef=useRef<MediaStream|null>(null); const timerRef=useRef<ReturnType<typeof setInterval>|null>(null); const sendingRef=useRef(false);

  useEffect(()=>{const load=async()=>{try{const [d,i]=await Promise.all([fetch(`${API}/api/dashboard`),fetch(`${API}/api/incidents`)]);if(!d.ok||!i.ok)throw new Error();setDashboard(await d.json());setIncidents(await i.json());setApiOnline(true)}catch{setApiOnline(false)}};load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);

  useEffect(()=>{try{const s=new EventSource(`${API}/api/stream/events`);es.current=s;s.onopen=()=>setStream("connected");s.onerror=()=>setStream("disconnected");s.addEventListener("border-event",e=>{const p=JSON.parse((e as MessageEvent).data);if(p.kind==="detection")setLive(p.detections??[]);if(p.kind==="incident"){setIncidents(xs=>[{id:`LIVE-${p.track_id}`,type:p.type,camera_id:p.camera_id,sector:"Live feed",timestamp:new Date(p.timestamp*1000).toISOString(),object_type:p.object_type,track_id:String(p.track_id),confidence:p.confidence??0,risk_score:p.risk_score,severity:p.severity,status:"UNRESOLVED",reason:["AI vision event","Realtime border rule"]},...xs].slice(0,10))}});return()=>s.close()}catch{setStream("disconnected")}},[]);

  const refreshDevices=async()=>{try{const all=await navigator.mediaDevices.enumerateDevices();const cams=all.filter(d=>d.kind==="videoinput").map(d=>({deviceId:d.deviceId,label:d.label||`Camera ${d.deviceId.slice(0,6)}`}));setDevices(cams);if(!deviceId&&cams[0])setDeviceId(cams[0].deviceId)}catch{setCameraError("Unable to list cameras. Check browser camera permission.")}};

  const stopLiveCamera=()=>{if(timerRef.current){clearInterval(timerRef.current);timerRef.current=null}mediaRef.current?.getTracks().forEach(t=>t.stop());mediaRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setCameraRunning(false);setLive([]);setCameraError("")};

  const sendFrame=async()=>{if(sendingRef.current||!videoRef.current||videoRef.current.readyState<2)return;const video=videoRef.current;const canvas=canvasRef.current;if(!canvas||!video.videoWidth)return;sendingRef.current=true;canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext("2d")?.drawImage(video,0,0,canvas.width,canvas.height);try{const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/jpeg",0.72));if(!blob)throw new Error("Frame encoding failed");const response=await fetch(`${API}/api/live/CAM-02/frame`,{method:"POST",headers:{"Content-Type":"image/jpeg"},body:blob});if(!response.ok)throw new Error(`Live inference returned ${response.status}`);const data=await response.json();setLive(data.detections??[]);setStream("connected")}catch(error){setCameraError(error instanceof Error?error.message:"Live camera request failed")}finally{sendingRef.current=false}};

  const startLiveCamera=async()=>{setCameraError("");try{stopLiveCamera();const constraints:MediaStreamConstraints={video:deviceId?{deviceId:{exact:deviceId},width:{ideal:1280},height:{ideal:720}}:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}},audio:false};const media=await navigator.mediaDevices.getUserMedia(constraints);mediaRef.current=media;if(videoRef.current){videoRef.current.srcObject=media;await videoRef.current.play()}setCameraRunning(true);await refreshDevices();timerRef.current=setInterval(sendFrame,700)}catch(error){setCameraRunning(false);setCameraError(error instanceof DOMException&&error.name==="NotAllowedError"?"Camera permission was denied. Allow camera access in the browser and try again.":error instanceof Error?error.message:"Unable to start camera")}};

  useEffect(()=>{refreshDevices();return()=>stopLiveCamera()},[]);

  const acknowledge=async()=>{if(!selected)return;const response=await fetch(`${API}/api/incidents/${selected.id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"ACKNOWLEDGED"})});if(response.ok){setSelected({...selected,status:"ACKNOWLEDGED"});setIncidents(xs=>xs.map(x=>x.id===selected.id?{...x,status:"ACKNOWLEDGED"}:x))}};

  return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">B</div><div><strong>BorderSight</strong><span>AI COMMAND CENTER</span></div></div><nav className="nav"><a className="active" href="#">Overview</a><a href="#cameras">Cameras</a><a href="#incidents">Incidents</a><a href="#sectors">Sectors</a><a href="#analytics">Analytics</a></nav><div className="sidebar-footer">SIH 2026 · PS 187<br/>Operational prototype</div></aside>
  <main className="main"><header className="topbar"><div><div className="eyebrow">Border surveillance / Operations</div><div className="title">Command Center</div><div className="subtitle">Real-time situational awareness across monitored sectors.</div></div><div className="status"><span className="dot"/>{apiOnline?"SYSTEM ONLINE":"DEMO MODE"} · SSE {stream}</div></header>
  <section className="stats"><div className="card"><div className="stat-label">CAMERAS</div><div className="stat-value">{dashboard?.cameras.total??24}</div><div className="stat-meta">{dashboard?.cameras.online??21} online</div></div><div className="card"><div className="stat-label">ACTIVE INCIDENTS</div><div className="stat-value">{dashboard?.incidents.active??3}</div><div className="stat-meta">requires attention</div></div><div className="card"><div className="stat-label">CRITICAL</div><div className="stat-value">{dashboard?.incidents.critical??2}</div><div className="stat-meta">priority alerts</div></div><div className="card"><div className="stat-label">EVENTS TODAY</div><div className="stat-value">{dashboard?.events_today??147}</div><div className="stat-meta">AI observations</div></div></section>
  <section className="panel" id="cameras"><div className="panel-head"><div><div className="panel-title">Live surveillance</div><div className="panel-meta">Source: {source} · browser camera → AI inference</div></div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><select value={deviceId} onChange={e=>{setDeviceId(e.target.value);setCameraRunning(false)}} style={{background:"#0b1923",color:"#a9bbc5",border:"1px solid #294150",borderRadius:7,padding:"8px 10px",maxWidth:220}} disabled={cameraRunning}><option value="">Default camera</option>{devices.map(d=><option key={d.deviceId} value={d.deviceId}>{d.label}</option>)}</select><button onClick={cameraRunning?stopLiveCamera:startLiveCamera} style={{padding:"8px 12px",background:cameraRunning?"#44212a":"#173c4d",border:"1px solid #2c647c",color:"#d8f5ff",borderRadius:7,cursor:"pointer"}}>{cameraRunning?"Stop live camera":"Start live camera"}</button></div></div>
  {cameraError&&<div style={{margin:"0 20px 12px",padding:"10px 12px",border:"1px solid #6b3440",borderRadius:7,color:"#f0b4bf",fontSize:12}}>{cameraError}</div>}
  <div className="live-stage" style={{position:"relative",overflow:"hidden"}}><video ref={videoRef} muted playsInline autoPlay style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover",display:cameraRunning?"block":"none"}}/><canvas ref={canvasRef} style={{display:"none"}}/><div className="stage-grid"/><div className="virtual-line"/><span className="line-label">RESTRICTED BOUNDARY</span>{live.map((d,i)=>{const b=d.bbox;return <div key={`${d.track_id}-${i}`} className="detection" style={{left:`${(b?.[0]??0)/6}%`,top:`${(b?.[1]??0)/4}%`,width:`${Math.max(5,((b?.[2]??0)-(b?.[0]??0))/6)}%`,height:`${Math.max(10,((b?.[3]??0)-(b?.[1]??0))/4)}%`}}><span>{d.label.toUpperCase()} #{d.track_id??"?"} · {Math.round(d.confidence*100)}%</span></div>})}<div className="camera-placeholder" style={{display:cameraRunning?"none":"grid"}}><div className="camera-icon">◉</div><strong>{live.length?`${live.length} tracked objects`:"Live camera ready"}</strong><small>Choose a camera above and start the live AI stream</small></div><div className="feed-state">● {cameraRunning?"LIVE AI INFERENCE":"CAMERA READY"}</div></div></section>
  <section className="grid"><div className="panel" id="incidents"><div className="panel-head"><div className="panel-title">Priority incidents</div><div className="panel-meta">{incidents.length} records</div></div><div className="incident-list">{incidents.map(i=><button key={i.id} onClick={()=>setSelected(i)} style={{background:"none",border:0,color:"inherit",width:"100%",textAlign:"left",cursor:"pointer"}}><div className="incident"><div className="incident-row"><div><div className="incident-name">{i.type.replaceAll("_"," ")}</div><div className="incident-time">{i.id} · {i.camera_id}</div></div><span className={`severity ${i.severity!=="CRITICAL"?"medium":""}`}>{i.severity}</span></div><div className="incident-detail">{i.reason.join(" · ")}</div><div className="bar"><span style={{width:`${i.risk_score}%`}}/></div></div></button>)}</div></div>
  <div className="panel"><div className="panel-head"><div className="panel-title">Detection activity</div><div className="panel-meta">Realtime</div></div><div style={{padding:20}}><div className="stat-label">CURRENT TRACKS</div><div className="stat-value" style={{marginTop:8}}>{live.length}</div><div className="stat-meta">objects reported by AI engine</div><div style={{marginTop:25}} className="stat-label">INPUT PIPELINE</div>{["Browser / phone camera","JPEG frame ingestion","YOLO detection + tracking","Realtime event stream","Incident evaluation"].map((x,i)=><div key={x} style={{padding:"10px 0",borderBottom:"1px solid #182d39",fontSize:12}}><span className="dot" style={{display:"inline-block",marginRight:8}}/> {x}<span style={{float:"right",color:"#76909d"}}>{cameraRunning&&i<4?"LIVE":"READY"}</span></div>)}</div></div></section>
  <section className="panel" id="sectors"><div className="panel-head"><div className="panel-title">Sector status</div><div className="panel-meta">Risk overview</div></div>{(dashboard?.sectors??[{name:"Sector A",status:"CRITICAL",incidents:5},{name:"Sector B",status:"ELEVATED",incidents:3},{name:"Sector C",status:"NORMAL",incidents:1}]).map(s=><div className="sector" key={s.name}><div><div className="sector-name">{s.name}</div><small>{s.incidents} active events</small></div><div className={`sector-status ${s.status.toLowerCase()}`}>● {s.status}</div></div>)}</section><div className="footer-note">AI observations are decision-support signals. Verify incidents against original video before operational action.</div></main>
  {selected&&<div onClick={()=>setSelected(null)} style={{position:"fixed",inset:0,background:"#0008",display:"grid",placeItems:"center",padding:20}}><div onClick={e=>e.stopPropagation()} className="card" style={{width:"min(520px,100%)",background:"#0b1923",borderColor:"#294150"}}><div className="eyebrow">Incident investigation</div><h2 style={{margin:"8px 0",fontSize:21}}>{selected.type.replaceAll("_"," ")}</h2><div style={{color:"#718896",fontSize:12}}>{selected.id} · {selected.camera_id} · {selected.sector}</div><div style={{marginTop:20,display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{[["Risk score",`${selected.risk_score}/100`],["Severity",selected.severity],["Object",selected.object_type],["Track",selected.track_id],["Confidence",`${Math.round(selected.confidence*100)}%`],["Status",selected.status]].map(([a,b])=><div key={a} className="card" style={{padding:12}}><div className="stat-label">{a}</div><div style={{marginTop:5,fontSize:13,fontWeight:600}}>{b}</div></div>)}</div><div style={{marginTop:16,fontSize:11,color:"#8095a2"}}>Why flagged</div><ul style={{color:"#b8c6ce",fontSize:12,lineHeight:1.8,paddingLeft:18}}>{selected.reason.map(r=><li key={r}>{r}</li>)}</ul><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:18}}><button onClick={()=>setSelected(null)} style={{padding:"9px 13px",background:"transparent",border:"1px solid #294150",color:"#9db0bc",borderRadius:7}}>Close</button>{selected.status==="UNRESOLVED"&&<button onClick={acknowledge} style={{padding:"9px 13px",background:"#173c4d",border:"1px solid #2c647c",color:"#d8f5ff",borderRadius:7}}>Acknowledge</button>}</div></div></div>}</div>
}
